/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_bobpaulin_osgi_dll_HelloWorld */

#ifndef _Included_com_bobpaulin_osgi_dll_HelloWorld
#define _Included_com_bobpaulin_osgi_dll_HelloWorld
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_bobpaulin_osgi_dll_HelloWorld
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_bobpaulin_osgi_dll_HelloWorld_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
